version: '3.8'

services:
  app:
    build:
      dockerfile: dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - cache
      - database

  cache:
    image: redis:7.2.4-alpine3.19
    restart: always
    environment:
      - REDIS_PORT=6379
    volumes:
      - redis:/data
    ports:
      - "6380:6379"
  
  database:
    image: postgres:15.6-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rss_reader
      - POSTGRES_PASSWORD=rss_reader_dev
      - POSTGRES_DB=rss_reader
    ports:
      - "5433:5432"
    user: postgres

volumes:
  redis:
    driver: local
  postgres_data:
    driver: local