"""add fk relationship for feed and posts

Revision ID: 5ecddbaaf9ef
Revises: 9c7caadfc0a5
Create Date: 2024-05-11 21:34:51.701304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecddbaaf9ef'
down_revision: Union[str, None] = '9c7caadfc0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('feed_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'feeds', ['feed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'feed_id')
    # ### end Alembic commands ###
