"""adding relationships

Revision ID: ec5b435db10a
Revises: fba595352b27
Create Date: 2024-05-05 19:34:40.419289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5b435db10a'
down_revision: Union[str, None] = 'fba595352b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_items', sa.Column('feed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feed_items', 'feeds', ['feed_id'], ['id'])
    op.add_column('feeds', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feeds', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feeds', type_='foreignkey')
    op.drop_column('feeds', 'user_id')
    op.drop_constraint(None, 'feed_items', type_='foreignkey')
    op.drop_column('feed_items', 'feed_id')
    # ### end Alembic commands ###
